dist: trusty
language: node_js
node_js:
  - "9"
addons:
  chrome: stable
before_install:
  - # start your web application and listen on `localhost`
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
#before_install:
#  - "curl -L https://raw.githubusercontent.com/arunoda/travis-ci-laika/master/configure.sh | /bin/sh"
#services:
#  - mongodb
#env:
#  - LAIKA_OPTIONS="-t 5000"
